# indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr1= np.array([10,20,30,40,50,60])

In [3]:
arr1[4]

50

In [4]:
arr1[-1]

60

In [5]:
len(arr1)

6

In [6]:
#negative indexing

In [8]:
arr1[-2]

50

In [9]:
arr1[-5]

20

In [10]:
#slicing

In [12]:
arr1[0:2]

array([10, 20])

In [13]:
arr1[3:6]

array([40, 50, 60])

In [15]:
arr1[:]

array([10, 20, 30, 40, 50, 60])

In [16]:
arr1[0:]

array([10, 20, 30, 40, 50, 60])

In [17]:
arr1[:5]

array([10, 20, 30, 40, 50])

In [18]:
arr1[-5:-2]

array([20, 30, 40])

In [19]:
#slicing with step

In [21]:
arr1[0:6:2]

array([10, 30, 50])

In [23]:
arr1[::-1]

array([60, 50, 40, 30, 20, 10])

In [24]:
#slicing using list

In [25]:
l1 = [1,4]

In [26]:
arr1[l1]

array([20, 50])