# Numpy arrays

In [7]:
import numpy as np
list1 = [1,2,3,'a',True]

In [8]:
list1

[1, 2, 3, 'a', True]

In [9]:
arr1=np.array(list1)

In [10]:
arr1

array(['1', '2', '3', 'a', 'True'], dtype='<U11')

In [13]:
arr2 = np.array([1,2,3,4,5,5.6])

In [14]:
arr2

array([1. , 2. , 3. , 4. , 5. , 5.6])

In [16]:
arr3= np.array([1,2,3,True])

In [17]:
arr3

array([1, 2, 3, 1])

In [18]:
arr4= np.array([1,2,3,False])

In [19]:
arr4

array([1, 2, 3, 0])